export const aaveLiquidityHookAbi = [
  {
    inputs: [],
    name: "HookPaused",
    type: "error",
  },
  {
    inputs: [],
    name: "InvalidPool",
    type: "error",
  },
  {
    inputs: [{ internalType: "address", name: "account", type: "address" }],
    name: "OwnableUnauthorizedAccount",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "PoolId", name: "poolId", type: "bytes32" },
      { indexed: false, internalType: "address", name: "aToken", type: "address" },
      { indexed: false, internalType: "address", name: "underlying", type: "address" },
    ],
    name: "PoolConfigSet",
    type: "event",
  },
  {
    inputs: [],
    name: "TARGET_IN_POOL_BPS",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "aavePool",
    outputs: [{ internalType: "contract IPool", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getHookPermissions",
    outputs: [
      {
        components: [
          { internalType: "bool", name: "beforeInitialize", type: "bool" },
          { internalType: "bool", name: "afterInitialize", type: "bool" },
          { internalType: "bool", name: "beforeAddLiquidity", type: "bool" },
          { internalType: "bool", name: "afterAddLiquidity", type: "bool" },
          { internalType: "bool", name: "beforeRemoveLiquidity", type: "bool" },
          { internalType: "bool", name: "afterRemoveLiquidity", type: "bool" },
          { internalType: "bool", name: "beforeSwap", type: "bool" },
          { internalType: "bool", name: "afterSwap", type: "bool" },
          { internalType: "bool", name: "beforeDonate", type: "bool" },
          { internalType: "bool", name: "afterDonate", type: "bool" },
          { internalType: "bool", name: "beforeSwapReturnDelta", type: "bool" },
          { internalType: "bool", name: "afterSwapReturnDelta", type: "bool" },
          { internalType: "bool", name: "afterAddLiquidityReturnDelta", type: "bool" },
          { internalType: "bool", name: "afterRemoveLiquidityReturnDelta", type: "bool" },
        ],
        internalType: "struct Hooks.Permissions",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "paused",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "PoolId", name: "", type: "bytes32" }],
    name: "poolConfigs",
    outputs: [
      { internalType: "address", name: "aToken", type: "address" },
      { internalType: "address", name: "underlying", type: "address" },
      { internalType: "uint256", name: "deployedToAave", type: "uint256" },
      { internalType: "bool", name: "isToken0", type: "bool" },
      { internalType: "bool", name: "initialized", type: "bool" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "poolManager",
    outputs: [{ internalType: "contract IPoolManager", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "PoolId", name: "poolId", type: "bytes32" }],
    name: "emergencyWithdrawAll",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "renounceOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "bool", name: "_paused", type: "bool" }],
    name: "setPaused",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "PoolId", name: "poolId", type: "bytes32" },
      { internalType: "address", name: "aToken", type: "address" },
      { internalType: "address", name: "underlying", type: "address" },
      { internalType: "bool", name: "isToken0", type: "bool" },
    ],
    name: "setPoolConfig",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "newOwner", type: "address" }],
    name: "transferOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;
