export const swapSingletonAbi = [
  { inputs: [], stateMutability: "nonpayable", type: "constructor" },
  { inputs: [], name: "AlreadyMatched", type: "error" },
  { inputs: [], name: "AlreadySettled", type: "error" },
  { inputs: [], name: "InsufficientMargin", type: "error" },
  { inputs: [], name: "MarketExpired", type: "error" },
  { inputs: [], name: "MarketNotActive", type: "error" },
  { inputs: [], name: "NotLiquidatable", type: "error" },
  { inputs: [], name: "NotSettled", type: "error" },
  { inputs: [{ internalType: "address", name: "owner", type: "address" }], name: "OwnableInvalidOwner", type: "error" },
  { inputs: [{ internalType: "address", name: "account", type: "address" }], name: "OwnableUnauthorizedAccount", type: "error" },
  { inputs: [], name: "ReentrancyGuardReentrantCall", type: "error" },
  { inputs: [{ internalType: "address", name: "token", type: "address" }], name: "SafeERC20FailedOperation", type: "error" },
  { inputs: [], name: "ZeroNotional", type: "error" },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint256", name: "positionId", type: "uint256" },
      { indexed: false, internalType: "address", name: "floatingReceiver", type: "address" },
      { indexed: false, internalType: "uint256", name: "marginRequired", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "bounty", type: "uint256" },
    ],
    name: "FloatingSideTaken",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint256", name: "positionId", type: "uint256" },
      { indexed: false, internalType: "address", name: "liquidator", type: "address" },
      { indexed: false, internalType: "uint256", name: "bounty", type: "uint256" },
    ],
    name: "LiquidationExecuted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint256", name: "marketId", type: "uint256" },
      { indexed: false, internalType: "address", name: "underlyingAsset", type: "address" },
      { indexed: false, internalType: "uint256", name: "termEnd", type: "uint256" },
      { indexed: false, internalType: "address", name: "oracle", type: "address" },
    ],
    name: "MarketCreated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "previousOwner", type: "address" },
      { indexed: true, internalType: "address", name: "newOwner", type: "address" },
    ],
    name: "OwnershipTransferred",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint256", name: "positionId", type: "uint256" },
      { indexed: true, internalType: "uint256", name: "marketId", type: "uint256" },
      { indexed: false, internalType: "address", name: "fixedReceiver", type: "address" },
      { indexed: false, internalType: "uint256", name: "notional", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "fixedRate", type: "uint256" },
    ],
    name: "SwapOpened",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint256", name: "positionId", type: "uint256" },
      { indexed: false, internalType: "int256", name: "netAmount", type: "int256" },
      { indexed: false, internalType: "uint256", name: "timestamp", type: "uint256" },
    ],
    name: "SwapSettled",
    type: "event",
  },
  {
    inputs: [
      { internalType: "address", name: "underlyingAsset", type: "address" },
      { internalType: "uint256", name: "termEnd", type: "uint256" },
      { internalType: "uint256", name: "leverageMultiplier", type: "uint256" },
      { internalType: "address", name: "oracle", type: "address" },
      { internalType: "uint256", name: "liquidationThresholdBps", type: "uint256" },
    ],
    name: "createMarket",
    outputs: [{ internalType: "uint256", name: "marketId", type: "uint256" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "marketId", type: "uint256" }],
    name: "deactivateMarket",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "positionId", type: "uint256" }],
    name: "liquidate",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "markets",
    outputs: [
      { internalType: "address", name: "underlyingAsset", type: "address" },
      { internalType: "uint256", name: "termEnd", type: "uint256" },
      { internalType: "uint256", name: "leverageMultiplier", type: "uint256" },
      { internalType: "address", name: "oracle", type: "address" },
      { internalType: "uint256", name: "liquidationThresholdBps", type: "uint256" },
      { internalType: "bool", name: "active", type: "bool" },
    ],
    stateMutability: "view",
    type: "function",
  },
  { inputs: [], name: "nextMarketId", outputs: [{ internalType: "uint256", name: "", type: "uint256" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "nextPositionId", outputs: [{ internalType: "uint256", name: "", type: "uint256" }], stateMutability: "view", type: "function" },
  {
    inputs: [
      { internalType: "uint256", name: "marketId", type: "uint256" },
      { internalType: "uint256", name: "notional", type: "uint256" },
      { internalType: "bool", name: "", type: "bool" },
      { internalType: "address", name: "onBehalfOf", type: "address" },
    ],
    name: "openSwap",
    outputs: [{ internalType: "uint256", name: "positionId", type: "uint256" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  { inputs: [], name: "owner", outputs: [{ internalType: "address", name: "", type: "address" }], stateMutability: "view", type: "function" },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "positions",
    outputs: [
      { internalType: "uint256", name: "marketId", type: "uint256" },
      { internalType: "address", name: "fixedReceiver", type: "address" },
      { internalType: "address", name: "floatingReceiver", type: "address" },
      { internalType: "uint256", name: "notional", type: "uint256" },
      { internalType: "uint256", name: "fixedRateBps", type: "uint256" },
      { internalType: "uint256", name: "fixedMargin", type: "uint256" },
      { internalType: "uint256", name: "floatingMargin", type: "uint256" },
      { internalType: "uint256", name: "liquidationBounty", type: "uint256" },
      { internalType: "uint256", name: "entryIndex", type: "uint256" },
      { internalType: "uint256", name: "openTimestamp", type: "uint256" },
      { internalType: "bool", name: "settled", type: "bool" },
      { internalType: "bool", name: "floatingSideTaken", type: "bool" },
    ],
    stateMutability: "view",
    type: "function",
  },
  { inputs: [], name: "renounceOwnership", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ internalType: "uint256", name: "positionId", type: "uint256" }], name: "settlePosition", outputs: [], stateMutability: "nonpayable", type: "function" },
  {
    inputs: [
      { internalType: "uint256", name: "positionId", type: "uint256" },
      { internalType: "address", name: "onBehalfOf", type: "address" },
    ],
    name: "takeFloatingSide",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  { inputs: [{ internalType: "address", name: "", type: "address" }], name: "totalCollateral", outputs: [{ internalType: "uint256", name: "", type: "uint256" }], stateMutability: "view", type: "function" },
  { inputs: [{ internalType: "address", name: "newOwner", type: "address" }], name: "transferOwnership", outputs: [], stateMutability: "nonpayable", type: "function" },
] as const;
